InsuranceLicensePackage/src/objects/Custom_License_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>does not contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>includes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>excludes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Custom License Rule</label>
    <nameField>
        <label>Custom License Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom License Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InsuranceLicensePackage/src/objects/Custom_License_Rule_Logic__c.object
<CustomObject>
    <fields>
        <fullName>Logic__c</fullName>
        <label>Logic</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Custom License Rule Logic</label>
    <nameField>
        <label>Custom License Rule Logic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom License Rule Logics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InsuranceLicensePackage/src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NPN_Number__c</fullName>
        <label>NPN Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>License Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nevada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Hampshire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Insurance License</label>
    <nameField>
        <label>License Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

InsuranceLicensePackage/src/objects/Standard_License_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Standard License Rule</label>
    <nameField>
        <label>Standard License Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard License Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InsuranceLicensePackage/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>NPN_Number__c</fullName>
        <externalId>true</externalId>
        <label>NPN Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

InsuranceLicensePackage/src/classes/LicenseRuleTestDataSeeder.cls
public with sharing class LicenseRuleTestDataSeeder {
    
    public static final String ACCOUNT_OBJ = 'Account';
    public static final String CASE_OBJ = 'Case';
    public static final String OPPORTUNITY_OBJ = 'Opportunity';
    
    public static Map<String, List<Map<String, String>>> cfieldsByObj = new Map<String, List<Map<String, String>>>();
    public static Map<String, List<Map<String, String>>> sfieldsByObj = new Map<String, List<Map<String, String>>>();
        
    private static Map<String, Schema.RecordTypeInfo> licenseRecordTypes = Schema.SObjectType.License__c.getRecordTypeInfosByName();

    static {
    	List<Map<String, String>> accountCFieldsList = new List<Map<String, String>>();
    	cfieldsByObj.put(ACCOUNT_OBJ, accountCFieldsList);
    	
    	Map<String, String> accountFieldsMap1 = new Map<String, String>();
    	accountFieldsMap1.put('field__c', 'Name');
    	accountFieldsMap1.put('value__c', 'Test1234');
    	accountFieldsMap1.put('operator__c', 'equals');    	
    	accountCFieldsList.add(accountFieldsMap1);
    	
    	Map<String, String> accountFieldsMap2 = new Map<String, String>();
    	accountFieldsMap2.put('field__c', 'Rating');
    	accountFieldsMap2.put('value__c', 'hot,warm');
    	accountFieldsMap2.put('operator__c', 'includes');    	
    	accountCFieldsList.add(accountFieldsMap2);
    	
    	Map<String, String> accountFieldsMap3 = new Map<String, String>();
    	accountFieldsMap3.put('field__c', 'LastmodifiedDate');
    	accountFieldsMap3.put('value__c', '2005-10-08T01:02:03Z');
    	accountFieldsMap3.put('operator__c', 'greater than');    	
    	accountCFieldsList.add(accountFieldsMap3);
    	
    	List<Map<String, String>> accountSFieldsList = new List<Map<String, String>>();
    	sfieldsByObj.put(ACCOUNT_OBJ, accountSFieldsList);
    	Map<String, String> accountSFieldsMap1 = new Map<String, String>();
    	accountSFieldsMap1.put('field__c', 'BillingState');
    	accountSFieldsMap1.put('type__c', StandardLicenseRuleValidator.STATE_RULE);
    	accountSFieldsList.add(accountSFieldsMap1);
    	
    }
    
    public static List<Custom_License_Rule__c> createValidCustomLicenseRules(String objName) {
    	return createValidCustomLicenseRules(objName, true);
    }
    
    public static List<Custom_License_Rule__c> createValidCustomLicenseRules(String objName, Boolean isActive) {
    	List<Map<String, String>> objFieldsList = cfieldsByObj.get(objName);
    	List<Custom_License_Rule__c> rules = new List<Custom_License_Rule__c>();
    	
    	for (Map<String, String> objFields : objFieldsList) {
    		Custom_License_Rule__c rule = new Custom_License_Rule__c(
	    		object__c=objName,
	    		field__c=objFields.get('field__c'),
	    		operator__c=objFields.get('operator__c'),
	    		value__c=objFields.get('value__c'),
	    		isActive__c=isActive
    		);
    		
    		rules.add(rule);
    	}

    	insert rules; 
    	
    	return rules;	
    }
    
    public static Custom_License_Rule_Logic__c createValidCustomLicenseRuleLogic(List<Custom_License_Rule__c> rules, String objName) {
    	Custom_License_Rule_Logic__c validLogic = new Custom_License_Rule_Logic__c(
    		object__c=objName,
    		logic__c=String.format('({0} OR {1}) AND {2}', new String[]{rules.get(0).id, rules.get(1).id, rules.get(2).id})
    	);
    	insert validLogic;
    	
    	return validLogic;
    }
    
    public static Map<String, Standard_License_Rule__c> createValidStandardLicenseRule(String objName) {
    	return createValidStandardLicenseRule(objName, true);
    }
    
    public static Map<String, Standard_License_Rule__c> createValidStandardLicenseRule(String objName, Boolean isActive) {
    	List<Map<String, String>> objFieldsList = sfieldsByObj.get(objName);
    	List<Standard_License_Rule__c> rules = new List<Standard_License_Rule__c>();
    	Map<String, Standard_License_Rule__c> ruleByType = new Map<String, Standard_License_Rule__c>();
    	
    	for (Map<String, String> objFields : objFieldsList) {
    		Standard_License_Rule__c rule = new Standard_License_Rule__c(
	    		object__c=objName,
	    		field__c=objFields.get('field__c'), 
	    		type__c=objFields.get('type__c'),
	    		isActive__c=isActive
	    	);
	    	rules.add(rule);
	    	ruleByType.put(rule.type__c, rule);
    	}
    	
    	insert rules;
    	
    	return ruleByType;	
    }
    
    public static License__c createLicense(String ownerId, String state) {
    	License__c license = new License__c(
	        	OwnerId = ownerId, 
	            Name = 'CA License', 
	            RecordtypeId = licenseRecordTypes.get('Resident State').getRecordTypeId(), 
	            Number__c = '123', 
	            NPN_Number__c  = '123', 
	            Confirmation_ID__c = '123', 
	            State__c = state, 
	            Effective_Date__c = Date.today().addDays(-1), 
	            Expiration_Date__c = Date.today().addDays(1),
                approved__c = true
	        );
	   	
	   	insert license;     
	    return license; 
    }
    
    public static User createUser() {
    	Profile sp = [SELECT Id FROM profile WHERE name='System Administrator'];
        User testUser = new User(alias = 'uxxx1', email='this.coly@gmail.com', emailencodingkey='UTF-8', firstname='FN', lastname='Testing', 
          languagelocalekey='en_US', localesidkey='en_US', profileid = sp.Id, country='United States',
          timezonesidkey='America/Los_Angeles', username='test654CBA@test.com'); 
          
        insert testUser;
        return testUser;
    }
}