InsuranceLicensePackage/src/objects/License_Rule_Logic__c.object
<CustomObject>
    <fields>
        <fullName>Filter_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Filter Rule</label>
        <referenceTo>License_Rule_Logic__c</referenceTo>
        <relationshipLabel>License Rule Logics (Filter Rule)</relationshipLabel>
        <relationshipName>Filter_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Logic__c</fullName>
        <label>Logic</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>License Rule Logic</label>
    <nameField>
        <label>License Rule Logic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Rule Logics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InsuranceLicensePackage/src/classes/LicenseRuleLogicValidator.cls
public with sharing class LicenseRuleLogicValidator extends RuleValidator{
    
    public LicenseRuleLogicValidator(LicenseRuleHelper ruleHelper) {
    	super(ruleHelper);
    }
    
    public void validate(License_Rule_Logic__c ruleLogic, Map<String, Set<String>> ruleIdsByObjName, Map<String, Set<String>> filterRuleLogicIdsByObjName) {    	
    	String logic = ruleLogic.logic__c;
    	String objName = ruleLogic.object__c;
    	
    	Set<String> ruleIdArray = ruleHelper.getRuleIdArray(logic);
    	Set<String> ruleIds = ruleIdsByObjName.get(objName);
    	
    	if (ruleIds==null || ruleIds.isEmpty()) {
    		String errorMessage = RuleValidator.errorMessageByType.get(RuleValidator.RuleError.RULE_LOGIC_FOUND);
    		throw new LicenseRuleException(String.format(errorMessage, new String[]{objName}));
    	} else {   		
    		for (String ruleId : ruleIdArray) {
    			if (!ruleIds.contains(ruleId)) {
    				String errorMessage = RuleValidator.errorMessageByType.get(RuleValidator.RuleError.RULE_NOT_FOUND);
					throw new LicenseRuleException(String.format(errorMessage, new String[]{ 'Rule', logic, ruleId}));
    			}
    		}
    	} 
    	
    	Set<String> filterRuleLogicIds = filterRuleLogicIdsByObjName.get(objName);
    	//verify license rule logic points to filter rule logic only if filter rule logic exists
    	if (ruleLogic.recordTypeId == LicenseRuleHelper.licenseRuleLogicRecordTypeId) {
    		if ((filterRuleLogicIds == null || filterRuleLogicIds.isEmpty()) && ruleLogic.filter_rule__c!=null) {
    			String errorMessage = RuleValidator.errorMessageByType.get(RuleValidator.RuleError.ONLY_LICENSE_FILTER_COMPARISON_RULE);
				throw new LicenseRuleException(String.format(errorMessage, new String[]{ruleLogic.id}));
    		}
    	}
    }
}