InsuranceLicensePackage/src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NPN_Number__c</fullName>
        <label>NPN Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>License Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nevada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Hampshire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Insurance License</label>
    <nameField>
        <label>License Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

InsuranceLicensePackage/src/classes/LicenseControllerTest.cls
@isTest
public class LicenseControllerTest {
    public static testMethod void testLDupeLicense() {
        License__c residentlicense = new License__c(
            State__c = 'California',
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Resident State').getRecordTypeId(),
            Confirmation_ID__c = '123',
            NPN_Number__c = '123',
            Number__c = '123',
            Effective_Date__c = Date.today().addDays(-1),
            Expiration_Date__c = Date.today());
        insert residentlicense;
        try {
            License__c residentlicense2 = new License__c(
                State__c = 'California',
                RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Resident State').getRecordTypeId(),
                Confirmation_ID__c = '123',
                NPN_Number__c = '123',
                Number__c = '123',
                Effective_Date__c = Date.today().addDays(-1),
                Expiration_Date__c = Date.today());
            insert residentlicense2;
            System.assert(false, 'Shouldn\'t get here.');
        } catch(Exception e) {
            System.assert(true, 'It works!');
        }
    }

    public static testMethod void testLicenseControllerSet() {
        License__c residentlicense = new License__c(
            State__c = 'California',
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Resident State').getRecordTypeId(),
            Confirmation_ID__c = '123',
            NPN_Number__c = '123',
            Number__c = '123',
            Approved__c = true,
            Effective_Date__c = Date.today().addDays(-1),
            Expiration_Date__c = Date.today());
        insert residentlicense;
        License__c nonResidentlicense = new License__c(
            State__c = 'Nebraska',
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Non-Resident State').getRecordTypeId(),
            Confirmation_ID__c = '123',
            NPN_Number__c = '123',
            Number__c = '123',
            Approved__c = true,
            Effective_Date__c = Date.today().addDays(-1),
            Expiration_Date__c = Date.today());
        insert nonResidentlicense;

        Test.setCurrentPage(Page.License_List);
        
        List<License__c> licenses = new List<License__c>();
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(licenses);
        LicenseSetController lsc = new LicenseSetController(ssc);
    }

    public static testMethod void testNewResident() {        
        Test.startTest();
        
        Test.setCurrentPage(Page.License_Edit);
        
        License__c license = new License__c(
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Resident State').getRecordTypeId());
        
        ApexPages.StandardController sc = new ApexPages.StandardController(license);
        LicenseController lc = new LicenseController(sc);
        
        license.Application_Date__c = Date.today();
        license.Confirmation_ID__c = '123';
        
        System.assertNotEquals(sc.save(), null);
        
        lc.viewList();
        
        Test.stopTest();
    }
    
    public static testMethod void testNewNonResidentWithoutResident() {
        License__c residentlicense = new License__c(
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Resident State').getRecordTypeId(),
            Confirmation_ID__c = '123');
        insert residentlicense;
        
        Test.startTest();
        
        Test.setCurrentPage(Page.License_Edit);
        
        License__c license = new License__c(
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Non-Resident State').getRecordTypeId());
        
        ApexPages.StandardController sc = new ApexPages.StandardController(license);
        LicenseController lc = new LicenseController(sc);
        
        System.assertEquals(lc.allowed, false, 'Resident State is incomplete, so should fail');
        
        Test.stopTest();
    }
    
    public static testMethod void testNewNonResidentWithResident() {
        License__c residentlicense = new License__c(
            State__c = 'California',
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Resident State').getRecordTypeId(),
            Confirmation_ID__c = '123',
            NPN_Number__c = '123',
            Number__c = '123',
            Approved__c = true,
            Effective_Date__c = Date.today().addDays(-1),
            Expiration_Date__c = Date.today());
        insert residentlicense;
        
        Test.startTest();
        
        Test.setCurrentPage(Page.License_Edit);
        
        License__c license = new License__c(
            RecordTypeId = Schema.SObjectType.License__c.getRecordTypeInfosByName().get('Non-Resident State').getRecordTypeId());
        
        ApexPages.StandardController sc = new ApexPages.StandardController(license);
        LicenseController lc = new LicenseController(sc);
        
        System.assertEquals(lc.allowed, true, 'Resident State is complete, so should not fail');
        
        license.State__c = 'Nebraska';
        license.Confirmation_ID__c = '123';
        
        System.assertNotEquals(sc.save(), null, ApexPages.getMessages());
        
        Test.stopTest();
    }
}