InsuranceLicensePackage/src/objects/License_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Field__c</fullName>
        <label>License Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>does not contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>equals</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not blank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>License Rule</label>
    <nameField>
        <label>License Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InsuranceLicensePackage/src/classes/LicenseRuleValidatorTest.cls
@isTest
private class LicenseRuleValidatorTest {
    
    static testmethod void testValidateLicenseRule() {
    	License_Rule__c comparisonRuleTypeNotSame = new License_Rule__c
    		(Object__c = 'Opportunity', field__c = 'closeDate', license_Field__c = 'name', operator__c = 'greater than', isActive__c = true, recordTypeId = LicenseRuleHelper.licenseComparisonRuleRecordTypeId);
    	
    	 License_Rule__c startsWithRuleShouldNotBeBoolean = new License_Rule__c(Object__c = 'Account', field__c = 'isDeleted', value__c = 'test', operator__c = 'starts with', isActive__c = true, recordTypeId = LicenseRuleHelper.regularFilterRuleRecordTypeId);                      
    	 
    	 License_Rule__c inRuleShouldNotBeBoolean = new License_Rule__c(Object__c = 'Account', field__c = 'isDeleted', value__c = 'test', operator__c = 'in', isActive__c = true, recordTypeId = LicenseRuleHelper.regularFilterRuleRecordTypeId);                      
    	 
    	 License_Rule__c invalidBooleanRule = new License_Rule__c(Object__c = 'Account', field__c = 'isDeleted', value__c = 'test', operator__c = 'equals', isActive__c = true, recordTypeId = LicenseRuleHelper.regularFilterRuleRecordTypeId);                      
    	 License_Rule__c invalidDateRule = new License_Rule__c(Object__c = 'Opportunity', field__c = 'closedate', value__c = 'test', operator__c = 'greater than', isActive__c = true, recordTypeId = LicenseRuleHelper.regularFilterRuleRecordTypeId);                      
    	 License_Rule__c invalidDatetimeRule = new License_Rule__c(Object__c = 'Account', field__c = 'lastmodifieddate', value__c = 'test', operator__c = 'greater than', isActive__c = true, recordTypeId = LicenseRuleHelper.regularFilterRuleRecordTypeId);                      
    	 License_Rule__c invalidNumberRule = new License_Rule__c(Object__c = 'Account', field__c = 'numberOfEmployees', value__c = 'test', operator__c = 'greater than', isActive__c = true, recordTypeId = LicenseRuleHelper.regularFilterRuleRecordTypeId);                      
    	
    	try {
    		insert comparisonRuleTypeNotSame;
    		throw new LicenseRuleException('An exception should have been thrown by the trigger but was not.');
    	} catch (DMLException e) {
    		system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
    	}
    	
    	try {
    		insert startsWithRuleShouldNotBeBoolean;
    		throw new LicenseRuleException('An exception should have been thrown by the trigger but was not.');
    	} catch (DMLException e) {
    		system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
    	}
    	
    	try {
    		insert inRuleShouldNotBeBoolean;
    		throw new LicenseRuleException('An exception should have been thrown by the trigger but was not.');
    	} catch (DMLException e) {
    		system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
    	}
    	
    	try {
    		insert invalidBooleanRule;
    		throw new LicenseRuleException('An exception should have been thrown by the trigger but was not.');
    	} catch (DMLException e) {
    		system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
    	}
    	
    	try {
    		insert invalidDateRule;
    		throw new LicenseRuleException('An exception should have been thrown by the trigger but was not.');
    	} catch (DMLException e) {
    		system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
    	}
    	
    	try {
    		insert invalidDatetimeRule;
    		throw new LicenseRuleException('An exception should have been thrown by the trigger but was not.');
    	} catch (DMLException e) {
    		system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
    	}
    	
    	try {
    		insert invalidNumberRule;
    		throw new LicenseRuleException('An exception should have been thrown by the trigger but was not.');
    	} catch (DMLException e) {
    		system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
    	}		 
    }
}